{% set name = "yattag" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0978247b9754d9f44e3703c64374ab9fa872d18de95ac5772fdfdd3c3f0d0706

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - yattag
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.yattag.org
  dev_url: https://github.com/leforestier/yattag
  license: LGPL-2.1-only
  license_file:
    - license/COPYING
    - license/lgpl-2.1.txt
  summary: Generate HTML or XML in a pythonic way. Pure python alternative to web template engines.Can fill HTML forms with default values and error messages.

extra:
  recipe-maintainers:
    - pmgrafe
    - thewchan
