{% set name = "yattag" %}
{% set version = "1.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 960fa54be1229d96f43178133e0b195c003391fdc49ecdb6b69b7374db6be416

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.2
  run:
    - python >=3.2

test:
  imports:
    - yattag
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.yattag.org
  dev_url: https://github.com/leforestier/yattag
  license: LGPL-2.1-only
  license_file:
    - license/COPYING
    - license/lgpl-2.1.txt
  summary: Generate HTML or XML in a pythonic way. Pure python alternative to web template engines.Can fill HTML forms with default values and error messages.

extra:
  recipe-maintainers:
    - pmgrafe
    - thewchan
